### ISSUE TITLE
Error [ERR_STREAM_WRITE_AFTER_END]: write after end     while zipping large directories

### ISSUE THREAD

**Issue by tewk** [tanhauhau/express-easy-zip#1]
I worked around it by commending out the _this.end() call.

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:572:17)
    at ServerResponse.write (_http_outgoing.js:567:10)
    at module.exports.ondata (node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at module.exports.emit (events.js:182:13)
    at module.exports.Readable.read (node_modules/readable-stream/lib/_stream_readable.js:469:26)
    at flow (node_modules/readable-stream/lib/_stream_readable.js:813:34)
    at ServerResponse.<anonymous> (node_modules/readable-stream/lib/_stream_readable.js:683:7)
    at ServerResponse.emit (events.js:182:13)
    at Socket.ondrain (internal/http.js:21:44)
    at Socket.emit (events.js:187:15)
    at onwriteDrain (_stream_writable.js:490:12)
    at afterWrite (_stream_writable.js:478:5)
    at onwrite (_stream_writable.js:471:7)
    at WriteWrap.afterWrite [as oncomplete] (net.js:848:19)
Emitted 'error' event at:
    at writeAfterEndNT (_http_outgoing.js:631:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by tanhauhau** [comment]
PR is welcome

**Comment by NateRive** [comment]
This helped me. thank you

**Comment by josuearrieta** [comment]
Is this fixed ?

**Comment by blongstreth** [comment]
Can Blazzike's  pull request be added soon please since it is cleaned up and seems to resolve this issue?

**Comment by blongstreth** [comment]
Thank you very much for checking in the fix! After thinking about it, since `res.end()` is no longer being called explicitly, I assume the piping function ensures that the response is completed successfully (i.e. http response finalized and resources closed, etc).  Does that seem right to you?
